version: '3.5'

services:

  provisioning-app:
    container_name: test-task
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/test-task/'
      - '/test-task/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development